# Usa una imagen oficial de Python
FROM python:3.10-slim

# Setea el directorio de trabajo
WORKDIR /app

# Copia los archivos necesarios
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

# Expone el puerto 8080
EXPOSE 8080

# Comando para ejecutar la app
CMD ["gunicorn", "-b", "0.0.0.0:8080", "app:app"]
